config/routes.rb
Myinfo::Application.routes.draw do
  resources :messages
  root :to => 'dashboard#index'
  
  devise_for :users, :controllers => { :sessions => 'local_devise/sessions', 
                                       :registrations => 'local_devise/registrations', 
                                       :passwords => 'local_devise/passwords', 
                                       :omniauth_callbacks => 'local_devise/omniauth_callbacks'}
  devise_scope :users do
    get '/users', :to => 'dashboard#index', :as => :user_root
  end  

  match '/admin' => 'admin#index'
  match '/dashboard' => 'dashboard#index'
  match '/help' => 'help#index'

  match '/admin/add_new_user' => 'admin#add_new_user', :as => :add_new_user
  match '/admin/:id/update_user' => 'admin#update_user', :as => :update_user
  match '/admin/:id/delete_user' => 'admin#delete_user', :as => :delete_user

  match '/facebox/fb_edit_user' => 'facebox#fb_edit_user', :as => :fb_edit_user
  match '/facebox/fb_create_user' => 'facebox#fb_create_user', :as => :fb_create_user
  match '/facebox/fb_login' => 'facebox#fb_login', :as => :fb_login  
  match '/facebox/fb_reset_password' => 'facebox#fb_reset_password', :as => :fb_reset_password  

end

app/views/admin/partials/_add_user.html.erb
  <div id="add_user_errors">
  </div>
  <%= form_for User.new, :url => add_new_user_path, :html => { :class => "form-inline", :id => "admin_new_user", :data => { remote: true, spinner: "#new_user_spinner"} } do |f| %>
    <b><%= t(:add_new_user, scope: :'myinfo.titles') -%></b>
    <%= f.text_field :username, :class =>"input-medium", :placeholder => "Username", :autocomplete => "off", :id => "username" %>
    <%= f.email_field :email, :class =>"input-medium", :placeholder => "Email", :autocomplete => "off", :id => "email" %>
    <%= f.submit t(:save, scope: :'myinfo.buttons'), :class => "btn" %>&nbsp;<%= spinner_tag 'admin_new_user_spinner' %>
  <% end %>

app/views/admin/partials/_users.html.erb
<div id="best_in_place_errors"></div>

<table class="table table-hover table-condensed">
<thead>
  <tr>
    <!-- <th>#</th> -->
    <th><%= t(:username, scope: :'myinfo.headers') -%> <% if current_user.is_admin? -%><i class="icon-edit"><% end -%></i></th>
    <th><%= t(:email, scope: :'myinfo.headers') -%> <% if current_user.is_admin? -%><i class="icon-edit"><% end -%></i></th>
    <th><%= t(:role, scope: :'myinfo.headers') -%> <i class="icon-edit"></i></th>
    <th><%= t(:last_login, scope: :'myinfo.headers') -%></th>
    <th><%= t(:ip, scope: :'myinfo.headers') -%></th>
    <th><%= t(:login_count, scope: :'myinfo.headers').html_safe -%></th>
    <% if current_user.is_admin? -%><th></th><%end -%>
  </tr>
</thead>
<tbody>

<% roles =  (current_user.is_admin?) ? User.role_collection_with_admin : role_collection -%>

<% @users.each do |user| -%>
  <% not_current = !(user.username == current_user.username) ? true : false -%>
  <tr>
    <!-- <td><%= user.id %></td> -->
    <td><% if user.is_admin? -%><i class="icon-user"></i> <% end -%>
          <%= best_in_place_if (current_user.is_admin? and not_current), user, :username, :path => update_user_path(:id => user.id) %></td>
    <td><%= best_in_place_if (current_user.is_admin? and not_current), user, :email, :path => update_user_path(:id => user.id) %></td>
    <td><%= best_in_place_if not_current, user, :role, :type => :select, :collection => roles, :path => update_user_path(:id => user.id) %></td>
    <td><%= display_last_login(user) %></td>
    <td><%= display_last_ip(user) %></td>
    <td><%= user.sign_in_count if user.sign_in_count > 0 %></td>
    <% if current_user.is_admin? -%>
      <td>
      <% if not_current -%>
        <%= link_to image_tag("delete_12.png", :alt => "Delete"), delete_user_path(:id => user.id), {:title => t(:warning_deletes_user, scope: :'myinfo.messages'), :rel => :tooltip, :confirm => t(:confirm, scope: :'myinfo.messages'),  :method => :delete, :remote => true} %>
      <% end -%>
      </td>
    <%end -%>
  </tr>
<% end -%>
<tr><td colspan=8><i class="icon-edit"></i> <i><%= t(:click_to_edit_inline, scope: :'myinfo.messages') -%></i></td></tr>
</tbody>
</table>

<% if current_user.is_admin? -%>
  <%= render :partial => 'admin/partials/add_user' %>
<% end -%>