config/routes.rb
Myinfo::Application.routes.draw do
  resources :messages
  root :to => 'dashboard#index'
  
  devise_for :users, :controllers => { :sessions => 'local_devise/sessions', 
                                       :registrations => 'local_devise/registrations', 
                                       :passwords => 'local_devise/passwords', 
                                       :omniauth_callbacks => 'local_devise/omniauth_callbacks'}
  devise_scope :users do
    get '/users', :to => 'dashboard#index', :as => :user_root
  end  

  match '/admin' => 'admin#index'
  match '/dashboard' => 'dashboard#index'
  match '/help' => 'help#index'

  match '/admin/add_new_user' => 'admin#add_new_user', :as => :add_new_user
  match '/admin/:id/update_user' => 'admin#update_user', :as => :update_user
  match '/admin/:id/delete_user' => 'admin#delete_user', :as => :delete_user

  match '/facebox/fb_edit_user' => 'facebox#fb_edit_user', :as => :fb_edit_user
  match '/facebox/fb_create_user' => 'facebox#fb_create_user', :as => :fb_create_user
  match '/facebox/fb_login' => 'facebox#fb_login', :as => :fb_login  
  match '/facebox/fb_reset_password' => 'facebox#fb_reset_password', :as => :fb_reset_password  

end

app/views/layouts/partials/_footer.html.erb
Created by @Sudhir vishwakarma

app/views/layouts/partials/_navbar.html.erb
	  <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            Menu
          </a>
          <a class="brand" href="/dashboard">Internal Messaging System</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="<%= active_tab('dashboard') %>"><%= link_to t(:home, scope: :'myinfo.menu'), dashboard_path %></li>
            </ul>
            <ul class="nav pull-right">
              <li>
              <p class="navbar-text">
              <% if user_signed_in? -%>
                <%= link_to current_user.username, fb_edit_user_path, :remote => true %>&nbsp;|&nbsp; 
                <%= link_to t(:logout, scope: :'myinfo.menu'), destroy_user_session_path, :method=>'delete' %> 
              <% else -%>
                <%= link_to image_tag("sign-in-with-twitter-gray-20.png"), user_omniauth_authorize_path(:twitter) %>
                &nbsp;&nbsp;
                <%= link_to t(:login, scope: :'myinfo.menu'), fb_login_path, :remote => true %>&nbsp;|&nbsp;
                <%= link_to t(:sign_up, scope: :'myinfo.menu'), fb_create_user_path, :remote => true %>
              <% end -%>
              </p>
              </li>
            </ul>      
          </div>
        </div>
      </div>
    </div>